language: go
sudo: false
go:
  - 1.10.x
before_install:
  - go get golang.org/x/lint/golint
  - go get honnef.co/go/tools/cmd/staticcheck
jobs:
  include:
    - script: make all
    - stage: Run Test Coverage
      script: make cover
      after_success: bash <(curl -s https://codecov.io/bash)
    - stage: Build Release
      script:
        - make release
        - echo "Deploying to GitHub releases ..."
      deploy:
        provider: releases
        file:
          - cross/contained.af-darwin-amd64
          - cross/contained.af-darwin-amd64.md5
          - cross/contained.af-darwin-amd64.sha256
          - cross/contained.af-darwin-386
          - cross/contained.af-darwin-386.md5
          - cross/contained.af-darwin-386.sha256
          - cross/contained.af-freebsd-amd64
          - cross/contained.af-freebsd-amd64.md5
          - cross/contained.af-freebsd-amd64.sha256
          - cross/contained.af-freebsd-386
          - cross/contained.af-freebsd-386.md5
          - cross/contained.af-freebsd-386.sha256
          - cross/contained.af-linux-arm
          - cross/contained.af-linux-arm.md5
          - cross/contained.af-linux-arm.sha256
          - cross/contained.af-linux-arm64
          - cross/contained.af-linux-arm64.md5
          - cross/contained.af-linux-arm64.sha256
          - cross/contained.af-linux-amd64
          - cross/contained.af-linux-amd64.md5
          - cross/contained.af-linux-amd64.sha256
          - cross/contained.af-linux-386
          - cross/contained.af-linux-386.md5
          - cross/contained.af-linux-386.sha256
          - cross/contained.af-windows-amd64
          - cross/contained.af-windows-amd64.md5
          - cross/contained.af-windows-amd64.sha256
          - cross/contained.af-windows-386
          - cross/contained.af-windows-386.md5
          - cross/contained.af-windows-386.sha256
        skip_cleanup: true
        on:
          tags: true
        api_key:
          secure: "Qk30yVnHvX86lNcJ5saYwdDtxRfmENvv844mkOdlrjgDXwIOEdySR2puxKheQspZrzPLRMkDRDJHdXCY8fhT2770RxwUnHajMWqN8NmzzErI+xZjQYuRm5eiuauir9QDYA+4v6erp83XDsQuIm3dE5ISAUKSTfPG+aZX1hzH6vyV9Rh8XAUHWRdfLxTQ+ApWmf9Tpi/05VbdQYhRemxtkegR66sZ0uGvtcceccz0zs7UyuWLeuoDXT7gXCqILFb4zPL56Ds94ejO4fxNFZJtCjZpgO/z0pVhEe2Ij7/BZqloqwG72CxapU3/JnHrkOtBOAQb7JvjWSa9iu7UjMxqS/Mdvwllmk/GVfPcrlqgps7sN/CV6lPmF6y1OP9HREr8xd0mXd4z/75xraJU4oqBMMKox5OKVAO9MuIH19csFvEQ0BtslJtvEQUvHaxy8vWWq77YRmnZ2q4DJ3omiZYgdoXITmdaeHCWdl5w8Qwj4uAlcAxu8OFwXcy2G2i/XjE1Elru0VMa/aqHdtUQma+7sVmNknvHhTHFkIGBLb38df4T+eFAO60NLUXc8wK24STqrnS8FOY87rEzpf889ynx6mHDbrZZLZM5YXnmqcS0PrP5JHeJbVL1KZjwIWgHcmb3/qv7wPdlveLYfBbAYdI+zN/vG45VIZjRkka/PDUHzWw="
